name: Lint Dockerfile

on:
  workflow_call:
    inputs:
      dockerfile:
        description: 'Path to Dockerfile'
        type: string
        default: 'Dockerfile'

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ${{ inputs.dockerfile }}
          ignore: DL3033,DL3041
